//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pe.com.cibereletrik
{
    using System;
    using System.Collections.Generic;
    
    public partial class cliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cliente()
        {
            this.ticketpedido = new HashSet<ticketpedido>();
        }
    
        public int codcli { get; set; }
        public string nomcli { get; set; }
        public string apepcli { get; set; }
        public string apemcli { get; set; }
        public string doccli { get; set; }
        public string dircli { get; set; }
        public string telcli { get; set; }
        public string celcli { get; set; }
        public string corcli { get; set; }
        public bool estcli { get; set; }
        public int coddis { get; set; }
        public int codtipd { get; set; }
        public int codsex { get; set; }
    
        public virtual distrito distrito { get; set; }
        public virtual sexo sexo { get; set; }
        public virtual tipodocumento tipodocumento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ticketpedido> ticketpedido { get; set; }
    }
}
