//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pe.com.cibereletrik
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalleticketpedido
    {
        public int nrodet { get; set; }
        public int canent { get; set; }
        public decimal preent { get; set; }
        public int nroped { get; set; }
        public int codpro { get; set; }
    
        public virtual producto producto { get; set; }
        public virtual ticketpedido ticketpedido { get; set; }
    }
}
