//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pe.com.cibereletrik
{
    using System;
    using System.Collections.Generic;
    
    public partial class empleado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public empleado()
        {
            this.ticketpedido = new HashSet<ticketpedido>();
        }
    
        public int codemp { get; set; }
        public string nomemp { get; set; }
        public string apepemp { get; set; }
        public string apememp { get; set; }
        public string docemp { get; set; }
        public string diremp { get; set; }
        public string telemp { get; set; }
        public string celemp { get; set; }
        public string coremp { get; set; }
        public string usuemp { get; set; }
        public string claemp { get; set; }
        public bool estemp { get; set; }
        public int coddis { get; set; }
        public int codrol { get; set; }
        public int codtipd { get; set; }
        public int codsex { get; set; }
    
        public virtual distrito distrito { get; set; }
        public virtual rol rol { get; set; }
        public virtual sexo sexo { get; set; }
        public virtual tipodocumento tipodocumento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ticketpedido> ticketpedido { get; set; }
    }
}
