//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pe.com.cibereletrik
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class bdciberelectrik2026Entities : DbContext
    {
        public bdciberelectrik2026Entities()
            : base("name=bdciberelectrik2026Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<categoria> categoria { get; set; }
        public virtual DbSet<cliente> cliente { get; set; }
        public virtual DbSet<detalleticketpedido> detalleticketpedido { get; set; }
        public virtual DbSet<distrito> distrito { get; set; }
        public virtual DbSet<empleado> empleado { get; set; }
        public virtual DbSet<marca> marca { get; set; }
        public virtual DbSet<producto> producto { get; set; }
        public virtual DbSet<rol> rol { get; set; }
        public virtual DbSet<sexo> sexo { get; set; }
        public virtual DbSet<ticketpedido> ticketpedido { get; set; }
        public virtual DbSet<tipodocumento> tipodocumento { get; set; }
    
        public virtual int SP_ActualizarCategoria(Nullable<int> codigo, string nombre, Nullable<bool> estado)
        {
            var codigoParameter = codigo.HasValue ?
                new ObjectParameter("codigo", codigo) :
                new ObjectParameter("codigo", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var estadoParameter = estado.HasValue ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ActualizarCategoria", codigoParameter, nombreParameter, estadoParameter);
        }
    
        public virtual int SP_ActualizarMarca(Nullable<int> codigo, string nombre, Nullable<bool> estado)
        {
            var codigoParameter = codigo.HasValue ?
                new ObjectParameter("codigo", codigo) :
                new ObjectParameter("codigo", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var estadoParameter = estado.HasValue ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ActualizarMarca", codigoParameter, nombreParameter, estadoParameter);
        }
    
        public virtual int SP_ActualizarProducto(Nullable<int> codigo, string nombre, string descripcion, Nullable<decimal> precio, Nullable<int> cantidad, Nullable<System.DateTime> fecha, Nullable<bool> estado, Nullable<int> codcat, Nullable<int> codmar)
        {
            var codigoParameter = codigo.HasValue ?
                new ObjectParameter("codigo", codigo) :
                new ObjectParameter("codigo", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("descripcion", descripcion) :
                new ObjectParameter("descripcion", typeof(string));
    
            var precioParameter = precio.HasValue ?
                new ObjectParameter("precio", precio) :
                new ObjectParameter("precio", typeof(decimal));
    
            var cantidadParameter = cantidad.HasValue ?
                new ObjectParameter("cantidad", cantidad) :
                new ObjectParameter("cantidad", typeof(int));
    
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("fecha", fecha) :
                new ObjectParameter("fecha", typeof(System.DateTime));
    
            var estadoParameter = estado.HasValue ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(bool));
    
            var codcatParameter = codcat.HasValue ?
                new ObjectParameter("codcat", codcat) :
                new ObjectParameter("codcat", typeof(int));
    
            var codmarParameter = codmar.HasValue ?
                new ObjectParameter("codmar", codmar) :
                new ObjectParameter("codmar", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ActualizarProducto", codigoParameter, nombreParameter, descripcionParameter, precioParameter, cantidadParameter, fechaParameter, estadoParameter, codcatParameter, codmarParameter);
        }
    
        public virtual ObjectResult<SP_BuscarCategoriaXCodigo_Result> SP_BuscarCategoriaXCodigo(Nullable<int> codigo)
        {
            var codigoParameter = codigo.HasValue ?
                new ObjectParameter("codigo", codigo) :
                new ObjectParameter("codigo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_BuscarCategoriaXCodigo_Result>("SP_BuscarCategoriaXCodigo", codigoParameter);
        }
    
        public virtual ObjectResult<SP_BuscarMarcaXCodigo_Result> SP_BuscarMarcaXCodigo(Nullable<int> codigo)
        {
            var codigoParameter = codigo.HasValue ?
                new ObjectParameter("codigo", codigo) :
                new ObjectParameter("codigo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_BuscarMarcaXCodigo_Result>("SP_BuscarMarcaXCodigo", codigoParameter);
        }
    
        public virtual ObjectResult<SP_BuscarProductoXCodigo_Result> SP_BuscarProductoXCodigo(Nullable<int> codigo)
        {
            var codigoParameter = codigo.HasValue ?
                new ObjectParameter("codigo", codigo) :
                new ObjectParameter("codigo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_BuscarProductoXCodigo_Result>("SP_BuscarProductoXCodigo", codigoParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SP_CodigoCategoria()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_CodigoCategoria");
        }
    
        public virtual ObjectResult<Nullable<int>> SP_CodigoMarca()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_CodigoMarca");
        }
    
        public virtual ObjectResult<Nullable<int>> SP_CodigoProducto()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_CodigoProducto");
        }
    
        public virtual int SP_EliminarCategoria(Nullable<int> codigo)
        {
            var codigoParameter = codigo.HasValue ?
                new ObjectParameter("codigo", codigo) :
                new ObjectParameter("codigo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_EliminarCategoria", codigoParameter);
        }
    
        public virtual int SP_EliminarMarca(Nullable<int> codigo)
        {
            var codigoParameter = codigo.HasValue ?
                new ObjectParameter("codigo", codigo) :
                new ObjectParameter("codigo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_EliminarMarca", codigoParameter);
        }
    
        public virtual int SP_EliminarProducto(Nullable<int> codigo)
        {
            var codigoParameter = codigo.HasValue ?
                new ObjectParameter("codigo", codigo) :
                new ObjectParameter("codigo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_EliminarProducto", codigoParameter);
        }
    
        public virtual int SP_HabilitarCategoria(Nullable<int> codigo)
        {
            var codigoParameter = codigo.HasValue ?
                new ObjectParameter("codigo", codigo) :
                new ObjectParameter("codigo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_HabilitarCategoria", codigoParameter);
        }
    
        public virtual int SP_HabilitarMarca(Nullable<int> codigo)
        {
            var codigoParameter = codigo.HasValue ?
                new ObjectParameter("codigo", codigo) :
                new ObjectParameter("codigo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_HabilitarMarca", codigoParameter);
        }
    
        public virtual int SP_HabilitarProducto(Nullable<int> codigo)
        {
            var codigoParameter = codigo.HasValue ?
                new ObjectParameter("codigo", codigo) :
                new ObjectParameter("codigo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_HabilitarProducto", codigoParameter);
        }
    
        public virtual ObjectResult<SP_MostrarCategoria_Result> SP_MostrarCategoria()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MostrarCategoria_Result>("SP_MostrarCategoria");
        }
    
        public virtual ObjectResult<SP_MostrarCategoriaTodo_Result> SP_MostrarCategoriaTodo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MostrarCategoriaTodo_Result>("SP_MostrarCategoriaTodo");
        }
    
        public virtual ObjectResult<SP_MostrarMarca_Result> SP_MostrarMarca()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MostrarMarca_Result>("SP_MostrarMarca");
        }
    
        public virtual ObjectResult<SP_MostrarMarcaTodo_Result> SP_MostrarMarcaTodo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MostrarMarcaTodo_Result>("SP_MostrarMarcaTodo");
        }
    
        public virtual ObjectResult<SP_MostrarProducto_Result> SP_MostrarProducto()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MostrarProducto_Result>("SP_MostrarProducto");
        }
    
        public virtual ObjectResult<SP_MostrarProductoTodo_Result> SP_MostrarProductoTodo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MostrarProductoTodo_Result>("SP_MostrarProductoTodo");
        }
    
        public virtual int SP_RegistrarCategoria(string nombre, Nullable<bool> estado)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var estadoParameter = estado.HasValue ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_RegistrarCategoria", nombreParameter, estadoParameter);
        }
    
        public virtual int SP_RegistrarMarca(string nombre, Nullable<bool> estado)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var estadoParameter = estado.HasValue ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_RegistrarMarca", nombreParameter, estadoParameter);
        }
    
        public virtual int SP_RegistrarProducto(string nombre, string descripcion, Nullable<decimal> precio, Nullable<int> cantidad, Nullable<System.DateTime> fecha, Nullable<bool> estado, Nullable<int> codcat, Nullable<int> codmar)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("descripcion", descripcion) :
                new ObjectParameter("descripcion", typeof(string));
    
            var precioParameter = precio.HasValue ?
                new ObjectParameter("precio", precio) :
                new ObjectParameter("precio", typeof(decimal));
    
            var cantidadParameter = cantidad.HasValue ?
                new ObjectParameter("cantidad", cantidad) :
                new ObjectParameter("cantidad", typeof(int));
    
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("fecha", fecha) :
                new ObjectParameter("fecha", typeof(System.DateTime));
    
            var estadoParameter = estado.HasValue ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(bool));
    
            var codcatParameter = codcat.HasValue ?
                new ObjectParameter("codcat", codcat) :
                new ObjectParameter("codcat", typeof(int));
    
            var codmarParameter = codmar.HasValue ?
                new ObjectParameter("codmar", codmar) :
                new ObjectParameter("codmar", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_RegistrarProducto", nombreParameter, descripcionParameter, precioParameter, cantidadParameter, fechaParameter, estadoParameter, codcatParameter, codmarParameter);
        }
    }
}
