//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pe.com.cibereletrik
{
    using System;
    using System.Collections.Generic;
    
    public partial class producto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public producto()
        {
            this.detalleticketpedido = new HashSet<detalleticketpedido>();
        }
    
        public int codpro { get; set; }
        public string nompro { get; set; }
        public string despro { get; set; }
        public decimal prepro { get; set; }
        public int canpro { get; set; }
        public System.DateTime fecing { get; set; }
        public bool estpro { get; set; }
        public int codcat { get; set; }
        public int codmar { get; set; }
    
        public virtual categoria categoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalleticketpedido> detalleticketpedido { get; set; }
        public virtual marca marca { get; set; }
    }
}
