//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pe.com.cibereletrik
{
    using System;
    using System.Collections.Generic;
    
    public partial class ticketpedido
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ticketpedido()
        {
            this.detalleticketpedido = new HashSet<detalleticketpedido>();
        }
    
        public int nroped { get; set; }
        public System.DateTime fecped { get; set; }
        public int codemp { get; set; }
        public int codcli { get; set; }
        public bool estped { get; set; }
    
        public virtual cliente cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalleticketpedido> detalleticketpedido { get; set; }
        public virtual empleado empleado { get; set; }
    }
}
